#创建商品详情图片表 (hh_tatail_pics)
CREATE TABLE hh_tatail_pics(
	tid INT PRIMARY KEY AUTO_INCREMENT,
	pic1 VARCHAR(128),
	pic2 VARCHAR(128),
	pic3 VARCHAR(128),
	pic4 VARCHAR(128),
	pic5 VARCHAR(128),
	pic6 VARCHAR(128),
	pic7 VARCHAR(128),
	pic8 VARCHAR(128),
	pic9 VARCHAR(128),
	picb1 VARCHAR(128),
	picb2 VARCHAR(128),
	picb3 VARCHAR(128)
);
#插入商品详情图片内容(12个产品详情，117种单品，每10种公用1套)
INSERT INTO hh_tatail_pics VALUES (1,'product/tatail/fang/2j2CrQ2Mdp.jpg','product/tatail/fang/4WxYYEhM5t.jpg','product/tatail/fang/cmDpNizWKp.jpg','product/tatail/fang/CQk8Rr88T7.jpg','product/tatail/fang/j35Qd7GaYQ.jpg','product/tatail/fang/kT7cTYNZHK.jpg','product/tatail/fang/ncSzynTt52.jpg','product/tatail/fang/PGtX2SwmcM.jpg','product/tatail/fang/RKmyYr4Pd6.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (2,'product/tatail/zhen/64m5CdCCRH.jpg','product/tatail/zhen/J3kpNFCX4J.jpg','product/tatail/zhen/NcNz5sckkX.jpg','product/tatail/zhen/nnKQXhydGZ.jpg','product/tatail/zhen/pz2CMKixZY.jpg','product/tatail/zhen/tcQtSiBs6D.jpg','product/tatail/zhen/wrBNsH25Q8.jpg','product/tatail/zhen/yEYdpEYC55.jpg','product/tatail/zhen/zGzdcCZwPN.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (3,'product/tatail/xi98/4DbyjG8aQp.jpg','product/tatail/xi98/AK74sSwNBy.jpg','product/tatail/xi98/AQMK8QPPnw.jpg','product/tatail/xi98/cPwi7PJNAG.jpg','product/tatail/xi98/E3mAjCDi2C.jpg','product/tatail/xi98/rn4nE5scAC.jpg','product/tatail/xi98/sZ7YYKWFQQ.jpg','product/tatail/xi98/Te3bYM6FZN.jpg','product/tatail/xi98/wFxzZTi5jS.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (4,'product/tatail/zun/3jkn4tHaTF.jpg','product/tatail/zun/4TyYzbAdGY.jpg','product/tatail/zun/aDBQGRiyQQ.jpg','product/tatail/zun/AF2Sm3kFZc.jpg','product/tatail/zun/bApE3wRbeG.jpg','product/tatail/zun/ed4iQxmaSh.jpg','product/tatail/zun/h8TkZSBrFA.jpg','product/tatail/zun/tsxwWehCPy.jpg','product/tatail/zun/y2TzhTkB46.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (5,'product/tatail/jiang/4Z5PsBa3jw.jpg','product/tatail/jiang/ArCCJeePYC.jpg','product/tatail/jiang/FXNyMz4GJZ.jpg','product/tatail/jiang/KKrka86kWX.jpg','product/tatail/jiang/mTebKM4c6a.jpg','product/tatail/jiang/n53xknepRh.jpg','product/tatail/jiang/phCSRJedeM.jpg','product/tatail/jiang/PNMPBJjCrR.jpg','product/tatail/jiang/YzaKKd4jKW.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (6,'product/tatail/hong/2hEmTKfxpw.jpg','product/tatail/hong/A72WSZMcWG.jpg','product/tatail/hong/fAJRYW7Dnn.jpg','product/tatail/hong/k5HQXpdzQT.jpg','product/tatail/hong/n8jjdGm86G.jpg','product/tatail/hong/nJBmiCwE3b.jpg','product/tatail/hong/QZpN5wdwpN.jpg','product/tatail/hong/TyBt4DPfdf.jpg','product/tatail/hong/yCA4A5i6Zp.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (7,'product/tatail/dian/5c3D68YhBF.jpg','product/tatail/dian/8hhkeZRSrR.jpg','product/tatail/dian/8npfAKA5CK.jpg','product/tatail/dian/AQE6XzxWbC.jpg','product/tatail/dian/j8BdmEC4Ef.jpg','product/tatail/dian/MB5ECbTwdN.jpg','product/tatail/dian/TaBHdwR2Fx.jpg','product/tatail/dian/tj3PMiGtBB.jpg','product/tatail/dian/Y4fFPDybtC.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (8,'product/tatail/pin/a2sMab2WJP.jpg','product/tatail/pin/ff3A7y6emS.jpg','product/tatail/pin/G32H64cpGj.jpg','product/tatail/pin/JpcjaWKFKY.jpg','product/tatail/pin/kMd7pxtxat.jpg','product/tatail/pin/RX8rWZhkxX.jpg','product/tatail/pin/sxYPkDXPnX.jpg','product/tatail/pin/WPzswiR3Ps.jpg','product/tatail/pin/YTXdWZGGQC.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (9,'product/tatail/jin/6EhejaNdft.jpg','product/tatail/jin/azh785mrcD.jpg','product/tatail/jin/Kn5EPNejrK.jpg','product/tatail/jin/P5Yx3tfFGG.jpg','product/tatail/jin/pZPtDWrpj3.jpg','product/tatail/jin/R6C48PiNmh.jpg','product/tatail/jin/rH7dswByzj.jpg','product/tatail/jin/wxYSzJNsSP.jpg','product/tatail/jin/ZHraJ2h67f.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (10,'product/tatail/cang/4DbyjG8aQp.jpg','product/tatail/cang/AK74sSwNBy.jpg','product/tatail/cang/AQMK8QPPnw.jpg','product/tatail/cang/cPwi7PJNAG.jpg','product/tatail/cang/E3mAjCDi2C.jpg','product/tatail/cang/rn4nE5scAC.jpg','product/tatail/cang/sZ7YYKWFQQ.jpg','product/tatail/cang/Te3bYM6FZN.jpg','product/tatail/cang/wFxzZTi5jS.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (11,'product/tatail/gui/3bmkdBPWY7.jpg','product/tatail/gui/4bcBD4Ht4m.jpg','product/tatail/gui/8EtbARiNrz.jpg','product/tatail/gui/BGGkt4Brhz.jpg','product/tatail/gui/hCjK2E6tHB.jpg','product/tatail/gui/iJfceYm65n.jpg','product/tatail/gui/SG4jBKx5Db.jpg','product/tatail/gui/wmCdMpR8Z4.jpg','product/tatail/gui/ZW2CbymGGM.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');
INSERT INTO hh_tatail_pics VALUES (12,'product/tatail/yin/8aJhErmYCN.jpg','product/tatail/yin/ANTcmekGCP.jpg','product/tatail/yin/bxrJYbTEty.jpg','product/tatail/yin/E3QBrpBsCE.jpg','product/tatail/yin/eazi3XTtDb.jpg','product/tatail/yin/f27wNk8N2M.jpg','product/tatail/yin/fxXB6eEbHx.jpg','product/tatail/yin/GtPX6xxAkC.jpg','product/tatail/yin/zKEp5mDN56.jpg','product/tatail/public_tatail/PBER5rXYeK.jpg','product/tatail/public_tatail/cP3p53mtbF.jpg','product/tatail/public_tatail/hedEt8aKcb.jpg');

